### ISSUE TITLE
Colours are wrong in image widow.

### ISSUE THREAD

**Issue by elpidiovaldez** [leggedrobotics/darknet_ros#320]
It looks like an RGB/BGR issue is causing colours to be displayed incorrectly in the OpenCV window.  I see a similar issue #43 is marked as closed, but it still appears to be a problem.  I can't tell if this affects the image data (which could lower the recognition accuracy), or just the displayed image.

**Comment by tomlankhorst** [comment]
Please provide your OS, the commit hash that you're working on, and any other info that might be helpful.

**Comment by tomlankhorst** [comment]
Will likely be solved by #321 please continue discussion there.

**Comment by Wuxinxiaoshifu** [comment]
I also meet this problem!
when i training,the picture's format is rgb8. when i test the weights that i trained using bag,the colors of pictures in windows(yolo_v4) is different from my training pictures.
i also changed BGR8 to RGB8 in YoloObjectDetector.CPP, but the colors in window(yolo_v4) didn't change!
how did you handled this problem?

**Comment by elpidiovaldez** [comment]
I have not fixed it.  I have not tried anything beyond searching the
internet, because not a serious issue for me right now.
